# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d595223bcedf272eb777c4159ddb42c110a3b778538b6dee8bc593ace9cc62cbb9320eefe4476a38f6bebd0d030fc7aae004b151f77d0cd8fb4924726b5c118

test:
  secret_key_base: 3ace4c418ac4cc062bc9000c0a7c9b69766830bfa1ffbe8261dba9ce2abe2ebf00bd2d5ebfb89e3fa61f9d6f27f7eb85439ee5b0b214d652b16aae1d66a5bdd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
