# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e93ae3cc52915faac4b78f6704141bca9545eae4d4d6cdac0c2006af5520cfa5b6e1bfbc0affa4f340c716a61d3420a91c31386b16bcd4b59eb1626a520b55b

test:
  secret_key_base: 5e2a4daa8b162ec6348617b652e1efa6b03a40bec6040a2803f5292cc4a8c0fb3034234e917561d5faa4b923c3699c7e6ef3f19f0a46d18ea2d01ba8201024af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
